### ISSUE TITLE
Do you have a article about your greate work?

### ISSUE THREAD

**Issue by liyunlongaaa** [sinhat98/adapter-wavlm#1]

**Comment by sinhat98** [comment]
Sorry for the late reply. I will share a link to the paper shortly.

**Comment by liyunlongaaa** [comment]
thank you!

**Comment by sinhat98** [comment]
@liyunlongaaa 
We have published the paper of this work on arXiv. 
You can get the link to the paper from Note of README.

**Comment by liyunlongaaa** [comment]
thx!
